name: example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
   http_interceptor:
     path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
